# permissions for end users to view gonmaps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gonmap-viewer-role
rules:
- apiGroups:
  - mondo.github.io.clobaa
  resources:
  - gonmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mondo.github.io.clobaa
  resources:
  - gonmaps/status
  verbs:
  - get
